language: java
before_install:
  # download the latest android sdk and unzip
  - sudo apt-get update -qq
  - sudo apt-get install ia32-libs
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=~/builds/openxc/openxc-android/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list.  9 = 2.3.3 or API level 10
  - android update sdk --filter 1,2,3 --no-ui --force
install:
  - mvn install -DskipTests=true
notifications:
  hipchat: <%= ENV['HIPCHAT_TOKEN'] %>@Ford
env:
  global:
    secure: "iotiUK43hkNVsFw2WnL3DuvQTLnPj5vkYQ+R/L6I73rX/J2dMyMrjW3VPxA/\nj0cMgpMv1WCrt15qYfuuLO/kCPwedT6oD+zhAdM6REsy/Te0/4Hg5IPS3Lvd\nZ096QEg88wXbcJGaC7uVQ1nX1phIUBhu6LV37vBzOYChQIEwatE="
